version: '3'
services:
  golang:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/go_demo
    depends_on:
      - mongodb
    environment:
      - ENV_PROFILE
    tty: true
  mongodb:
    image: mongo
    command: mongod --bind_ip 0.0.0.0 --port 29017
    ports:
      - "29017:29017"
    volumes:
      - ../../mongodb/docker_demo:/data/db